import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`antialiased min-h-screen flex flex-col`}
      >
        <header>
          <nav className="flex">
            <Link href="/" className="p-2 rounded hover:bg-gray-100">
              메인
            </Link>
            <Link href="/posts" className="p-2 rounded hover:bg-gray-100">
              장바구니
            </Link>
            <Link href="/posts" className="p-2 rounded hover:bg-gray-100">
              관리자
            </Link>
          </nav>
        </header>
        <main className="flex-1 flex flex-col">{children}</main>
        <footer className="text-cneter p-2">
          <p>Copyright 2025. Site A. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
